version: '2'
services:
   db:
    image: mariadb
    environment:
      MYSQL_DATABASE: hubbit_dev
      MYSQL_USER: hubbit
      MYSQL_PASSWORD: iamapassword
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
   web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: bash -c "sh wait_for_db.sh && sh start.sh"
    ports:
      - "4000:3000"
    depends_on:
      - db
    volumes: 
      - .:/app
