version: '3'
services:
   db:
    image: mariadb
    environment:
      MYSQL_DATABASE: hubbit_dev
      MYSQL_USER: hubbit
      MYSQL_PASSWORD: iamapassword
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
   web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: bash -c 'rm -f tmp/pids/server.pid && sh wait_for_db.sh && sh start.sh'
    ports:
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    network_mode: host
